require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Rails:
  Enabled: true

Metrics:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/ExampleLength:
  Enabled: false
